// src/pages/Create/Create.vue
<template lang="pug">
  #create-page
    top-header(:current="current")
    p
    .container#app
        form#form
            .form-group
                label(for='name') 問卷名稱
                input#name.form-control(v-model="name" required="required")
                .invalid-feedback 請輸入問卷名稱
            .form-group
                label(for='description') 前導訊息
                textarea#description.form-control(rows="3" v-model="description" required="required")
                .invalid-feedback 請輸入前導訊息
            #questionField(:class="qValidation? '':'invalidQuestion'")
                .form-row
                    .form-group.col-md-6 題目
                    .form-group.col-md-2 類型
                    .form-group.col-md-3 選項
                    .form-group.col-md-1 必填
                question-component(v-for="(question, index) in questionArr" :key="index" :question="questionArr[index]" :index="index" :count="questionArr.length" @remove="removeQuestion(index)")
                div.btn.btn-primary(@click="addQuestion") 新增題目
            div
              small.text-danger {{qValidateMsg}}
            p
            .form-group
                label(for='finishMsg') 結束訊息
                textarea#finishMsg.form-control(rows="3" v-model="finishMsg" required=true)
                .invalid-feedback 請輸入結束訊息
            .form-group
                label(for='callBackUrl') Call back URL
                input#callBackUrl.form-control(v-model="callBackUrl")
            .form-group
                label(for='extraInfo') 其他
                textarea#extraInfo.form-control(rows="3" v-model="extraInfo")
            button#submit.btn.btn-primary(@click.prevent="validation") 送出
    .modal-success(v-if="success === true")
      .modal-body
        .success-banner
        .success-text 送出成功
</template>

<script>
import Header from '../../components/Header';
import Question from '../../components/Question'

export default {
  name: 'CreatePage',
  components: {
    TopHeader: Header,
    QuestionComponent: Question,
  },
  data: function() {
    return {
      current: 'create',
      success: false,
      questionCount: 1,
      name: '',
      description: '',
      finishMsg: '',
      callBackUrl: '',
      extraInfo: '',
      questionArr: [{
        topic: '',
        type: '單選題',
        options: [''],
        required: true,
      }],
      qValidateMsg: "",
      qValidation: true,
      success: false,
    }
  },
  methods: {
    addQuestion: function () {
        this.questionArr.push({
        topic: "",
        type: "單選題",
        options: [""],
        required: true
		})
    },
    removeQuestion: function (index) {
      this.questionArr.splice(index, 1)
    },
    submit: function () {
      const data = {
          name: this.name,
          description: this.description,
          questions: this.questionArr,
          finishMsg: this.finishMsg, 
          callBackUrl: this.callBackUrl,
          extraInfo: this.extraInfo,
          enabled: true,
      } 
      let host = window.location.hostname
      if(host !== "www.tbbt.com.tw"){
        host = "bg.ehanlin.com.tw"
      }
      let contextPath = ''
      fetch(`https://${host}${contextPath}/questionnaire/templates/create`,
					{			
					method:'post',
					headers: {
						'Content-Type':'application/json; charset=utf-8'
					},
					body: JSON.stringify(data),
					credentials: 'include',
					}).then(res => {
            console.log(res)
            if(res.type === 'cors' && res.status === 403){
                alert('請先登入')
                window.location.href="./index.html"
            }
            if(res.status === 200){
              this.success = true
              window.setTimeout(()=>{window.location.href="./templateList.html"},500)
            }
					}).catch(err => {
						console.log(err)
					})
    },
    validation: function(){
      this.validateQuestion()
      const form = document.getElementById('form')
      if (form.checkValidity() === false || this.qValidation === false) {
          event.preventDefault();
          event.stopPropagation();
          form.classList.add('was-validated');
      }else{
        this.submit()
      }
    },
    validateQuestion: function(){
      this.qValidation = true
      this.qValidateMsg = ""
      if(this.questionArr.length < 1){
        this.qValidateMsg += '至少要有一題問卷題目 '
        this.qValidation = false
      }
      this.questionArr.forEach(q => {
        if(q.type === '問答題'){
          q.options = null
        }
        if(q.topic === null || q.topic.trim() === ""){
          if(this.qValidateMsg.indexOf('題目不得為空 ') === -1){
            this.qValidateMsg += '題目不得為空 '
          }
          this.qValidation = false
        }
        if(q.type === '單選題' && q.options.length <= 1){
          if(this.qValidateMsg.indexOf('單選題至少要有一個以上的選項 ') === -1){
            this.qValidateMsg += '單選題至少要有一個以上的選項 '
          }
          this.qValidation = false
        }
        if(q.type === '多選題' && q.options.length <= 2){
          if(this.qValidateMsg.indexOf('多選題至少要有二個以上的選項 ') === -1){
            this.qValidateMsg += '多選題至少要有二個以上的選項 '
          }
          this.qValidation = false
        }
        if(q.options !== null){
          q.options.forEach(o => {
            if(o.trim() === ""){
              if(this.qValidateMsg.indexOf('選項不得為空 ') === -1){
                this.qValidateMsg += '選項不得為空 '
              }
              this.qValidation = false
            }
          })
        }
        if(document.getElementsByClassName("duplicateOption").length !== 0){
          this.qValidateMsg += "選項重複"
          this.qValidation = false
        }
      })
    },
  },
};
</script>

<style scoped>
  #questionField {
		background-color:#e3e3e3; 
		padding:15px; 
		border-radius:10px;
  }
	.invalidQuestion {
		border:1px solid red
	}
	.modal-success {
	z-index: 1000;
	position: absolute;
	top: 0;
	left: 0;
	width: 100%;
	height: 100%;
	background-color: #F5F5F5;
	-webkit-animation: show 1s forwards;
			animation: show 1s forwards; }
	.modal-success .success-banner {
		width: 100%;
		height: 240px;
		background-size: cover;
		background-position: center center; }
	.modal-success .success-text {
		text-align: center;
		padding: 30px 0px;
		color: #0D6CBE;
		font-size: 22px;
		font-weight: 500; }
	.modal-success .success-content {
		text-align: center;
    font-size: 14px; }
  ion-icon {
        font-size:25px;
        color:grey;
        height:38px;
        /* margin-left:60px; */
    }
</style>

// src/routes/create/index.svelte
	<script>
	import Question from './Question.svelte'
	import Validation from './Validation.svelte'
	const prefix = '/app/questionnaire'
    let questionCount = 1
    let name = ""
    let description = ""
    let finishMsg = ""
    let callBackUrl = ""
    let extraInfo = ""
    const question = {
        topic: "",
        type: "單選題",
        options: [""],
        required: true
    }
    $: questionArr = [question]

    function addQuestion(){
        console.log('add quesiton: ', questionArr)
        questionCount += 1
        questionArr.push({
        topic: "",
        type: "單選題",
        options: [""],
        required: true
		})
		questionArr = questionArr
	}
	
	function deleteQuestion(event){
		questionArr.splice(event.detail,1)
		questionArr = questionArr
		validateQuestion()
	}

	function submit(){
		const data = {
			name: name,
            description: description,
            questions: questionArr,
            finishMsg: finishMsg,
            callBackUrl: callBackUrl,
            extraInfo: extraInfo,
            enabled: true,
		}
		console.log('data ', JSON.stringify(data))
		fetch('https://www.tbbt.com.tw/questionnaire/templates/create',
		// fetch('http://localhost:8080/questionnaire/templates/create',
					{			
					method:'post',
					headers: {
						'Content-Type':'application/json; charset=utf-8'
					},
					body: JSON.stringify(data),
					credentials: 'include',
					}).then(res => {
						console.log(res)
						// window.location.href = prefix+"/templateList"
					}).catch(err => {
						console.log(err)
					})
	}
	let qValidation = true
	function validation(){
		console.log('validation')
		validateQuestion()
		const form = document.getElementById('form')
		if (form.checkValidity() === false || qValidation === false) {
				event.preventDefault();
				event.stopPropagation();
				form.classList.add('was-validated');
		}else{
			submit()
		}
	}
	let qValidateMsg
	function validateQuestion(){
		qValidation = true
		qValidateMsg = ""
		if(questionArr.length < 1){
			qValidateMsg += '至少要有一題問卷題目 '
			qValidation = false
		}
		questionArr.forEach(q => {
			if(q.type === '問答題'){
				q.options = null
			}
			if(q.topic === null || q.topic.trim() === ""){
				if(qValidateMsg.indexOf('題目不得為空 ') === -1){
					qValidateMsg += '題目不得為空 '
				}
				qValidation = false
			}
			if(q.type === '單選題' && q.options.length <= 1){
				if(qValidateMsg.indexOf('單選題至少要有一個以上的選項 ') === -1){
					qValidateMsg += '單選題至少要有一個以上的選項 '
				}
				qValidation = false
			}
			if(q.type === '多選題' && q.options.length <= 2){
				if(qValidateMsg.indexOf('多選題至少要有二個以上的選項 ') === -1){
					qValidateMsg += '多選題至少要有二個以上的選項 '
				}
				qValidation = false
			}
			if(q.options !== null){
				q.options.forEach(o => {
					if(o.trim() === ""){
						if(qValidateMsg.indexOf('選項不得為空 ') === -1){
							qValidateMsg += '選項不得為空 '
						}
						qValidation = false
					}
				})
			}
		})
	}

</script>


<style>
	#questionField {
		background-color:#e3e3e3; 
		padding:15px; 
		border-radius:10px;
	}
	.invalidQuestion {
		border:1px solid red
	}
</style>

<div class="container" id="app">
	<form class="needs-validation" id="form" novalidate>
		<div class="form-group">
			<label for="name">問卷名稱*</label>
			<input class="form-control" id="name" bind:value="{name}" required="required" />
			<Validation invalidMsg="請輸入問卷名稱"></Validation>
		</div>
		<div class="form-group">
			<label for="description">前導訊息*</label>
			<textarea class="form-control" id="description" bind:value="{description}" rows="3" required="required"></textarea>
			<Validation invalidMsg="請輸入前導訊息"></Validation>
		</div>
		<div class="{qValidation? '':'invalidQuestion'}" id="questionField">
			<div class="form-row">
				<div class="form-group col-md-6">題目</div>
				<div class="form-group col-md-2">類型</div>
				<div class="form-group col-md-3">選項</div>
				<div class="form-group col-md-1">必答</div>
			</div>
            {#each questionArr as question, q}
                <Question question="{questionArr[q]}" index="{q}" on:delete="{deleteQuestion}" {validateQuestion}/>
            {/each}
			<div class="btn btn-primary" style="margin-top:5px;" on:click="{addQuestion}">新增題目</div>
		</div>
		{#if qValidateMsg}
			<div><small class="text-danger">{qValidateMsg}</small></div>
		{/if}
		<p></p>
		<div class="form-group">
			<label for="finishMsg">結束訊息*</label>
			<textarea class="form-control" id="finishMsg" bind:value="{finishMsg}" rows="3" v-model="finishMsg" required="required"></textarea>
			<Validation invalidMsg="請輸入結束訊息"></Validation>
		</div>
		<div class="form-group">
			<label for="callBackUrl">Call back URL</label>
			<input class="form-control" id="callBackUrl" bind:value="{callBackUrl}" />
		</div>
		<div class="form-group">
			<label for="extraInfo">其他</label>
			<textarea class="form-control" id="extraInfo" rows="3" bind:value="{extraInfo}"></textarea>
		</div>
		<button class="btn btn-primary" id="submit" on:click|preventDefault="{validation}">送出 </button>
	</form>
</div>
