// back/src/components/Question/Question.vue
<template lang="pug">
    .form-row
        .form-group.col-md-6
            textarea#topic.form-control(type='text' v-model="question.topic" rows="1" :placeholder="index+1+'.'" required=true)
            .btn.btn-secondary.btn-sm(@click="removeQuestion" style="margin-top:3px" v-if="count !== 1") 刪除
        .form-group.col-md-2
            select#inputType.form-control(v-model="question.type")
                option(value="單選題") 單選題
                option(value="多選題") 多選題
                option(value="問答題") 問答題
        .form-group.col-md-3(v-if="question.type !== '問答題'")
            div(v-for=" (option, i) in question.options")
                div(style="display:flex")
                    input.form-control(:id="'inputOption'+i" type='text' v-model="question.options[i]" @blur="checkOption(question.options, option, i)")
                    ion-icon(name="trash" v-if=" question.options.length === 1" )                 
                    ion-icon(name="trash" @click="question.options.splice(i,1)" v-if=" question.options.length !== 1" )                
                ion-icon(name="add-circle-outline" @click="question.options.push('')" v-if=" i+1 === question.options.length")
        .form-group.col-md-1
            .form-check.form-check-inline
                input.form-check-input(type='checkbox', value="true" v-model="question.required") 
                | 是
</template>

<script>
export default {
    name: 'Question',
    props: ['question', 'index', 'count'],
    methods: {
        removeQuestion: function(){
            this.$emit('remove')
        },
        checkOption: function(optionArr, option, i){
        document.getElementById("inputOption"+i).classList.remove("duplicateOption")
        console.log(optionArr.indexOf(option))
        if(optionArr.indexOf(option) !== i){
            console.log('選項重複')
            document.getElementById("inputOption"+i).classList.add("duplicateOption")
        }
    }
    }
}
</script>

<style scoped>
    ion-icon {
        font-size: 25px;
        color:grey;
        height:38px;
    }
    ion-icon[name="add-circle-outline"] {
        display: block;
        margin: 0 40%;
    }
    .form-group.col-md-1 > .form-check-inline {
    margin-left: 25px;
    }
    .duplicateOption {
        border: 2px solid red !important;
    }
</style>

// src/routes/create/Question.svelte
<script>
    import Option from './Option.svelte'
    import { createEventDispatcher } from 'svelte';

    
    export let question = {
        topic : "",
        type : "單選題",
        options: [""],
        required : true,
    }
    export let index
    export let validateQuestion

    const dispatch = createEventDispatcher();
    
    function addOption(){
        question.options.push("")
        question.options = question.options
        console.log('options ',question.options)
    }
    function deleteOption(event){
        console.log('delete option: ', event.detail)
        question.options.splice(event.detail,1)
        question.options = question.options
        console.log(question.options)
        validateQuestion()
    }

    function toggleRequired(){
        question.required === true? false:true
    }

</script>

<style>
    ion-icon {
        font-size:25px;
        color:grey;
        height:38px;
        margin-left:60px;
    }
</style>

<div class="form-row">
	<div class="form-group col-md-6">
		<textarea class="form-control" id="topic" type="text" rows="1" bind:value={question.topic} required on:blur="{validateQuestion}"></textarea>
		<div class="btn btn-secondary btn-sm" style="margin-top:3px;" on:click="{() => dispatch('delete', index)}">刪除</div>
	</div>
	<div class="form-group col-md-2">
		<select class="form-control" id="inputType" bind:value="{question.type}" required on:change="{validateQuestion}">
			<option value="單選題">單選題</option>
			<option value="多選題">多選題</option>
			<option value="問答題">問答題</option>
		</select>
	</div>
    <div class="form-group col-md-3" id="options">
        {#if question.type !== '問答題'}
            {#each question.options as option, i}
                <Option count="{question.options.length}" index="{i}" on:delete="{deleteOption}">
                    <textarea rows="1" class="form-control" id="inputOption" bind:value="{question.options[i]}" required on:blur="{validateQuestion}"/>
                </Option>
            {/each}	
		    <ion-icon name="add-circle-outline" on:click="{addOption}"></ion-icon>	
        {/if}
    </div>
	<div class="form-group col-md-1">
		<div class="form-check form-check-inline" >
			<input class="form-check-input" type="checkbox" bind:checked="{ question.required }" on:change="{toggleRequired}" checked/>是
		</div>
	</div>
</div>
